[tool.mypy]
python_version = "3.11"
pretty = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
# More permissive settings for gradual typing
check_untyped_defs = false
disallow_untyped_calls = false
disallow_untyped_defs = false
no_implicit_optional = true
ignore_missing_imports = true

[tool.ruff]
target-version = "py311"
line-length = 88
lint.select = [
  "E",     # pycodestyle errors
  "W",     # pycodestyle warnings
  "F",     # pyflakes
  "I",     # isort
  "B",     # flake8-bugbear
  "C4",    # flake8-comprehensions
  "UP",    # pyupgrade
  "ARG",   # flake8-unused-arguments
  "PTH",   # flake8-use-pathlib
  "SIM",   # flake8-simplify
  "TID",   # flake8-tidy-imports
  "RET",   # flake8-return
  "FBT",   # flake8-boolean-trap
  "LOG",   # flake8-logging
  "RUF",   # ruff-specific rules
]
lint.ignore = [
  "E501",   # Line too long (let formatter handle)
  "FBT001", # Boolean positional arg in function definition
  "FBT002", # Boolean default value in function definition
  "FBT003", # Boolean positional value in function call
  "ARG001", # Unused function argument (common in Flask error handlers)
  "ARG002", # Unused method argument
]

[tool.ruff.lint.isort]
known-first-party = ["models", "routes", "utils"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Unused imports in init files are ok